theme: minima
title: Shuwen Tan
author: Shuwen Tan
email: shuwent@ldeo.columbia.edu
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my site! I am a Postdoctoral Fellow at Lamont-Doherty Earth Observatory, Columbia University.

# social links
LinkedIn_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ShuwenTan-PO # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
